# Identidad del proyecto en SonarQube Cloud (valores de TU cuenta)
sonar.organization=gregorio-mg
sonar.projectKey=gregorio-mg_reportaudit-lab
sonar.projectName=ReportAudit

# Qué se analiza y cómo
sonar.sources=app
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
